GoalsApp/config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :index, :destroy]
  resources :goals

  root to: "users#index"
end

GoalsApp/app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :author_id, presence: true
  validates :private_goal, inclusion: { in: [true, false] }
  validates :title, uniqueness: { scope: :author_id, message: "Can't repeat goals" }
  belongs_to :author, class_name: :User

  def private_goal?
    self.private_goal
  end

  def completed?
    self.completed
  end

end

GoalsApp/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true }
  has_many :goals, foreign_key: :author_id

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

GoalsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_token!
    @current_user = user
  end

  def logout!
    current_user.reset_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

end

GoalsApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_logged_in

  def index
    public_goals = Goal.all.where(private_goal: false)
        .where.not(user_id: current_user.id)
    our_goals = current_user.goals
    @goals = public_goals + our_goals
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.author_id = current_user.id #come back to break later
    if @goal.save
      redirect_to user_url(@goal.author_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private
  def goal_params
    params.require(:goal).permit(:description, :title, :private_goal, :completed)
  end
end

GoalsApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
                  params[:user][:username],
                  params[:user][:password]
                )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

GoalsApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # debugger
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalsApp/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalsApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

GoalsApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalsApp/app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

GoalsApp/app/views/goals/new.html.erb
<h1>Create New Goal</h1>

<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

<form action="<%= goals_url %>" method="post">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <label>Title
    <input type="string"
            name="goal[title]"
            value="<%= @goal.title %>">
  </label>

  <label>Description
    <textarea name="goal[description]" 
              rows="8"
              cols="40"><%= @goal.description %></textarea>
  </label>

  <label>Private?
    <select name="goal[private_goal]">
      <option value="true" id="private" >Private</option>
      <option value="false" id="public" selected >Public</option>
    </select>
  </label>

  <input type="submit" value="Create New Goal">

</form>

GoalsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if logged_in? %>
  <%= button_to "Sign Out", session_url, method: :delete %>
  <%= current_user.username %>
<% else %>
  <%= button_to "Sign In Page", new_session_url, method: :get %>
<% end %>

</body>
</html>

GoalsApp/app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_url(user) %></li>
  <% end %>
</ul>

GoalsApp/app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

<form action="<%= users_url %>" method="post">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <label for="username">Username: </label>
  <input type="text"
         name="user[username]"
         value="<%= @user.username %>"
         id="username">

  <label for="password">Password: </label>
  <input type="password" name="user[password]" id="password">

  <button type="submit" id="Sign Up">Sign Up</button>
</form>

GoalsApp/app/views/users/show.html.erb
<h1><%= @user.username  %></h1>

<ul>
  <% @user.goals.each do |goal| %>
    <li><%= goal.title %></li>
    <li><%= goal.description %></li>
  <% end %>
</ul